### ISSUE TITLE
 error TS2304: Cannot find name 'MediaStreamTrackAudioSourceNode'.

### ISSUE THREAD

**Issue by Mehranh** [ng-web-apis/audio#19]
After Migration from Angular 12 to 13, I get this error in compile-time,

Error: node_modules/@ng-web-apis/audio/sources/media-stream-track-source.d.ts:3:61 - error TS2304: Cannot find name 'MediaStreamTrackAudioSourceNode'.

3 export declare class WebAudioMediaStreamTrackSource extends MediaStreamTrackAudioSourceNode implements OnDestroy {
                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




× Failed to compile.
and I use this version of packages

"@ng-web-apis/audio": "^1.5.1",
"@ng-web-apis/common": "^1.12.1",
"@ng-web-apis/midi": "^1.2.0",
any idea?

**Comment by dominikks** [comment]
I am having the same issue with Angular 13 as well as 14: 

```
Error: node_modules/@ng-web-apis/audio/sources/media-stream-track-source.d.ts:3:61 - error TS2304: Cannot find name 'MediaStreamTrackAudioSourceNode'.

3 export declare class WebAudioMediaStreamTrackSource extends MediaStreamTrackAudioSourceNode implements OnDestroy {
                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```   

The workaround from @Mehranh works for me (thanks!), but I think the problem might be in the library.
